---
title: 'Normalization in Spatial Transcriptomics'
teaching: 15
exercises: 5
---

:::::::::::::::::::::::::::::::::::::: questions 

- Why is normalization necessary in spatial transcriptomics data analysis?
- What types of variability does normalization address in spatial transcriptomics datasets?
- How do normalization methods improve the biological interpretability of spatial transcriptomics data?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Understand the role of normalization in spatial transcriptomics to correct for technical variability.
- Explore various normalization methods used in spatial transcriptomics, such as log scaling and SCTransform.
- Discuss the impact of normalization on data comparability and biological insights in spatial transcriptomics research.

::::::::::::::::::::::::::::::::::::::::::::::::

## Why Normalize?

### Description of normalization techniques

### Data Interpretation

::::::::::::::::::::::::::::::::::::: challenge 

## Challenge 1: Analyze Normalized vs. Raw Data

Consider two datasets from the same spatial transcriptomics experiment: one raw and one normalized. What differences would you expect in the analysis results between these two datasets?

:::::::::::::::::::::::: solution 

Normalized data should show reduced variance due to technical factors and enhanced clarity in detecting biological differences. Raw data may exhibit skewed expression profiles influenced by technical artifacts.


::::::::::::::::::::::::

## Normalization Methods

::::::::::::::::::::::::::::::::::::: keypoints 

::::::::::::::::::::::::::::::::::::::::::::::::
