---
title: Spatially Resolved Transcriptomics in Life Sciences Research
teaching:
exercises:
---

:::::: questions
 - What is spatial transcriptomics? 
 - What research questions or problems can spatial transcriptomics address?
 - How do the technologies work?
 - Which technology will we learn about in this lesson?
::::::

:::::: objectives
 - Describe why and how spatial transcriptomics can be used in research.
 - Describe how spatial transcriptomics technology works. 
 - Describe how spatial transcriptomics addresses the limitations of single-cell or bulk RNA sequencing technologies. 
::::::

## Spatial transcriptomics in biomedical research
Investigating the arrangement of cells and tissues and its impact on function is 
fundamental to life sciences research. Spatially resolved transcriptomic methods 
provide positions of individual cells in a tissue and their transcriptomes. 
Since cell type and spatial organization are linked to biological activity,  
spatial information is critical for understanding cell and developmental 
biology, neurobiology, cancer biology and beyond.  


## Spatial transcriptomics technologies


## 10X Visium technology

:::::: keypoints
 - keypoint 1
 - keypoint 2
::::::
